export default [
    {
        _id: "6377ca1702df0fc167d07e29",
        name: "Ella King",
        username: "mcintosh",
        avatar: "https://avatars.dicebear.com/api/human/Minerva.png",
        createdAt: "2022-07-05T12:44:09",
        followers: 4469,
        followings: 427,
        points: 66666,
        description:
            "Nulla magna qui elit sit incididunt adipisicing adipisicing Lorem. Occaecat culpa velit do eu tempor non est cillum et exercitation dolore officia veniam.",
    },
    {
        _id: "6377ca176a0062abd161584d",
        name: "Duncan Morrison",
        username: "hall",
        avatar: "https://avatars.dicebear.com/api/human/Melton.png",
        createdAt: "2022-06-06T05:39:40",
        followers: 627,
        followings: 317,
        points: 38354,
        description:
            "Minim cupidatat est minim commodo id pariatur nulla. Sunt eu ipsum non magna ut aliqua duis cupidatat labore consequat sint.",
    },
    {
        _id: "6377ca17087cd808690314b8",
        name: "Decker Maldonado",
        username: "mayra",
        avatar: "https://avatars.dicebear.com/api/human/Greer.png",
        createdAt: "2022-09-03T06:24:21",
        followers: 1650,
        followings: 118,
        points: 1360,
        description:
            "Dolore irure ipsum do voluptate sint ex aliquip commodo. Eu culpa laborum irure incididunt commodo officia consectetur.",
    },
    {
        _id: "6377ca17aeab1d905d76e5e7",
        name: "Morse Martin",
        username: "rose",
        avatar: "https://avatars.dicebear.com/api/human/Newton.png",
        createdAt: "2022-08-23T03:45:23",
        followers: 4482,
        followings: 336,
        points: 76270,
        description:
            "Fugiat nostrud irure ex sunt mollit laborum est eiusmod est consectetur pariatur. Aute elit veniam pariatur elit.",
    },
    {
        _id: "6377ca17dd8db91b2f3772b4",
        name: "Elliott Weber",
        username: "roslyn",
        avatar: "https://avatars.dicebear.com/api/human/Reyna.png",
        createdAt: "2022-04-10T03:04:42",
        followers: 3729,
        followings: 116,
        points: 35264,
        description:
            "Incididunt sit enim Lorem nulla dolor sit proident. Ut anim ex sunt nulla aliquip officia dolor.",
    },
    {
        _id: "6377ca170d26e23ce7d02c54",
        name: "Roberts Burnett",
        username: "lynette",
        avatar: "https://avatars.dicebear.com/api/human/Rae.png",
        createdAt: "2022-03-23T11:16:25",
        followers: 3850,
        followings: 469,
        points: 11795,
        description:
            "Consectetur qui minim officia in exercitation quis non. Quis enim fugiat ut non.",
    },
    {
        _id: "6377ca17ecf48f870b5c6829",
        name: "Sosa Velazquez",
        username: "figueroa",
        avatar: "https://avatars.dicebear.com/api/human/Washington.png",
        createdAt: "2022-02-05T06:27:57",
        followers: 4552,
        followings: 221,
        points: 85386,
        description:
            "Est non nulla minim proident quis non. Pariatur consectetur id id excepteur duis ullamco id mollit nulla pariatur fugiat deserunt.",
    },
    {
        _id: "6377ca1761640fe29e945872",
        name: "Wooten Witt",
        username: "hanson",
        avatar: "https://avatars.dicebear.com/api/human/Gilmore.png",
        createdAt: "2022-05-01T08:07:20",
        followers: 3698,
        followings: 488,
        points: 37699,
        description:
            "Dolore velit exercitation anim id minim aute mollit ipsum. Quis nostrud officia esse reprehenderit.",
    },
    {
        _id: "6377ca17bd34bf46f0e70c72",
        name: "Holloway Poole",
        username: "stefanie",
        avatar: "https://avatars.dicebear.com/api/human/Marks.png",
        createdAt: "2022-03-18T02:09:02",
        followers: 1363,
        followings: 250,
        points: 90198,
        description:
            "Lorem culpa cupidatat ullamco id nisi ad. Duis cillum proident velit incididunt voluptate aliquip labore magna est.",
    },
    {
        _id: "6377ca17ec8493d0f05ff388",
        name: "Shannon Joyce",
        username: "peters",
        avatar: "https://avatars.dicebear.com/api/human/Rush.png",
        createdAt: "2022-09-28T06:12:44",
        followers: 909,
        followings: 199,
        points: 4196,
        description:
            "Non enim nostrud magna sunt ipsum quis laborum cupidatat Lorem officia do excepteur. Nulla consectetur nostrud nisi culpa commodo culpa eiusmod nisi ad consequat irure est ullamco deserunt.",
    },
    {
        _id: "6377ca17c4e0c5455de972d3",
        name: "Felicia Oneil",
        username: "daniel",
        avatar: "https://avatars.dicebear.com/api/human/Romero.png",
        createdAt: "2022-01-15T03:01:48",
        followers: 4529,
        followings: 5,
        points: 35962,
        description:
            "Exercitation exercitation excepteur nulla dolore esse voluptate ullamco consectetur laboris irure non consequat tempor. Excepteur labore consectetur do consectetur officia in.",
    },
    {
        _id: "6377ca17ac3351bc90a144e2",
        name: "Arline Mejia",
        username: "freeman",
        avatar: "https://avatars.dicebear.com/api/human/Rene.png",
        createdAt: "2022-03-16T06:02:54",
        followers: 1452,
        followings: 92,
        points: 69438,
        description:
            "Quis sint nisi proident enim consectetur duis occaecat dolor enim cupidatat commodo qui. Enim eiusmod adipisicing officia est nulla pariatur sunt sunt sit enim laborum irure ex sit.",
    },
    {
        _id: "6377ca17b325ead731a3a529",
        name: "Sabrina Ford",
        username: "kristi",
        avatar: "https://avatars.dicebear.com/api/human/Sophie.png",
        createdAt: "2022-05-14T03:13:17",
        followers: 517,
        followings: 22,
        points: 78878,
        description:
            "Elit duis minim irure aliqua consectetur enim ad elit sint culpa do nostrud in aute. Elit officia dolore eiusmod duis deserunt excepteur ut cillum veniam laborum esse tempor sint.",
    },
    {
        _id: "6377ca175c1c35c2fe1eff8c",
        name: "Mccall Daugherty",
        username: "eunice",
        avatar: "https://avatars.dicebear.com/api/human/Carly.png",
        createdAt: "2022-04-18T03:42:16",
        followers: 1980,
        followings: 71,
        points: 82426,
        description:
            "Irure ullamco amet do fugiat enim minim aliqua laboris. Eu occaecat nostrud non magna ipsum culpa voluptate.",
    },
    {
        _id: "6377ca172c5ee668a50657b1",
        name: "Agnes Terry",
        username: "grace",
        avatar: "https://avatars.dicebear.com/api/human/Huber.png",
        createdAt: "2022-09-21T10:49:12",
        followers: 312,
        followings: 100,
        points: 44866,
        description:
            "Sunt occaecat esse voluptate pariatur et amet adipisicing. Tempor ullamco et exercitation minim ea eiusmod incididunt non.",
    },
    {
        _id: "6377ca17da4b5f73f1f2e18c",
        name: "Josephine Gregory",
        username: "nellie",
        avatar: "https://avatars.dicebear.com/api/human/Douglas.png",
        createdAt: "2022-07-24T07:55:33",
        followers: 3011,
        followings: 478,
        points: 26316,
        description:
            "Pariatur excepteur pariatur sint sunt do. Ad ad consequat qui eu cupidatat aliqua minim.",
    },
    {
        _id: "6377ca173618da7f69379553",
        name: "Briana Ewing",
        username: "duffy",
        avatar: "https://avatars.dicebear.com/api/human/Haney.png",
        createdAt: "2022-11-08T07:37:20",
        followers: 4390,
        followings: 189,
        points: 4668,
        description:
            "Excepteur cillum consequat laborum aute. Sunt et nulla anim non non.",
    },
    {
        _id: "6377ca1783c1e1cb797e0344",
        name: "Pena Foster",
        username: "pate",
        avatar: "https://avatars.dicebear.com/api/human/Garcia.png",
        createdAt: "2022-05-06T02:51:48",
        followers: 496,
        followings: 442,
        points: 96761,
        description:
            "Qui exercitation culpa dolore culpa magna culpa. Culpa ea sit ad mollit duis in labore mollit sunt velit ex commodo laborum.",
    },
    {
        _id: "6377ca17f93ee217bb10b370",
        name: "Matilda Clark",
        username: "castro",
        avatar: "https://avatars.dicebear.com/api/human/Stokes.png",
        createdAt: "2022-08-29T10:57:26",
        followers: 1604,
        followings: 470,
        points: 99150,
        description:
            "Reprehenderit ut veniam occaecat magna nostrud est enim non excepteur ad laborum reprehenderit. Anim veniam consectetur excepteur nostrud irure sunt fugiat non.",
    },
    {
        _id: "6377ca17d115a06dd71787b4",
        name: "Ferguson Stevens",
        username: "amy",
        avatar: "https://avatars.dicebear.com/api/human/Aguilar.png",
        createdAt: "2022-04-20T09:23:37",
        followers: 4639,
        followings: 238,
        points: 29522,
        description:
            "Aliquip duis laboris in labore nulla pariatur velit. In est culpa ad eu.",
    },
];
